# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(350, 400)
        MainWindow.setMinimumSize(QtCore.QSize(350, 400))
        MainWindow.setMaximumSize(QtCore.QSize(350, 400))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_start = QtWidgets.QPushButton(self.centralwidget)
        self.btn_start.setGeometry(QtCore.QRect(10, 240, 331, 28))
        self.btn_start.setObjectName("btn_start")
        self.groupBox_statut = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_statut.setGeometry(QtCore.QRect(10, 80, 331, 61))
        self.groupBox_statut.setObjectName("groupBox_statut")
        self.lbl_status = QtWidgets.QLabel(self.groupBox_statut)
        self.lbl_status.setGeometry(QtCore.QRect(0, 20, 331, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_status.setFont(font)
        self.lbl_status.setAutoFillBackground(False)
        self.lbl_status.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_status.setObjectName("lbl_status")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 331, 61))
        self.groupBox_2.setObjectName("groupBox_2")
        self.pgr_level = QtWidgets.QProgressBar(self.groupBox_2)
        self.pgr_level.setGeometry(QtCore.QRect(10, 20, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pgr_level.setFont(font)
        self.pgr_level.setMinimum(0)
        self.pgr_level.setMaximum(4)
        self.pgr_level.setProperty("value", 0)
        self.pgr_level.setInvertedAppearance(False)
        self.pgr_level.setObjectName("pgr_level")
        self.groupBox_orientation = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_orientation.setGeometry(QtCore.QRect(10, 160, 331, 61))
        self.groupBox_orientation.setObjectName("groupBox_orientation")
        self.lbl_orientation = QtWidgets.QLabel(self.groupBox_orientation)
        self.lbl_orientation.setGeometry(QtCore.QRect(0, 20, 331, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_orientation.setFont(font)
        self.lbl_orientation.setAutoFillBackground(False)
        self.lbl_orientation.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_orientation.setObjectName("lbl_orientation")
        self.lbl_connection_status = QtWidgets.QLabel(self.centralwidget)
        self.lbl_connection_status.setGeometry(QtCore.QRect(70, 380, 55, 16))
        self.lbl_connection_status.setObjectName("lbl_connection_status")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 280, 331, 61))
        self.groupBox.setObjectName("groupBox")
        self.lineEdit_port_com = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_port_com.setGeometry(QtCore.QRect(50, 30, 101, 22))
        self.lineEdit_port_com.setObjectName("lineEdit_port_com")
        self.spinBox_baudrate = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_baudrate.setGeometry(QtCore.QRect(220, 30, 101, 22))
        self.spinBox_baudrate.setMaximum(256000)
        self.spinBox_baudrate.setProperty("value", 9600)
        self.spinBox_baudrate.setObjectName("spinBox_baudrate")
        self.lbl_baudrate = QtWidgets.QLabel(self.groupBox)
        self.lbl_baudrate.setGeometry(QtCore.QRect(160, 30, 55, 21))
        self.lbl_baudrate.setObjectName("lbl_baudrate")
        self.lbl_port = QtWidgets.QLabel(self.groupBox)
        self.lbl_port.setGeometry(QtCore.QRect(10, 30, 55, 21))
        self.lbl_port.setObjectName("lbl_port")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menu_serial_parameter = QtWidgets.QAction(MainWindow)
        self.menu_serial_parameter.setObjectName("menu_serial_parameter")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Boite Secrète"))
        self.btn_start.setText(_translate("MainWindow", "Démarrer"))
        self.groupBox_statut.setTitle(_translate("MainWindow", "Statut"))
        self.lbl_status.setText(_translate("MainWindow", "Hors ligne"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Niveau"))
        self.pgr_level.setFormat(_translate("MainWindow", "%v"))
        self.groupBox_orientation.setTitle(_translate("MainWindow", "Orientation de la boite"))
        self.lbl_orientation.setText(_translate("MainWindow", "A plat"))
        self.lbl_connection_status.setText(_translate("MainWindow", "TextLabel"))
        self.groupBox.setTitle(_translate("MainWindow", "Paramètres liaison série"))
        self.lineEdit_port_com.setText(_translate("MainWindow", "COM2"))
        self.lbl_baudrate.setText(_translate("MainWindow", "Vitesse :"))
        self.lbl_port.setText(_translate("MainWindow", "Port :"))
        self.menu_serial_parameter.setText(_translate("MainWindow", "Paramètres Série"))

