# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(350, 350)
        MainWindow.setMinimumSize(QtCore.QSize(350, 350))
        MainWindow.setMaximumSize(QtCore.QSize(350, 350))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_start = QtWidgets.QPushButton(self.centralwidget)
        self.btn_start.setGeometry(QtCore.QRect(10, 250, 331, 28))
        self.btn_start.setObjectName("btn_start")
        self.groupBox_statut = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_statut.setGeometry(QtCore.QRect(10, 90, 331, 61))
        self.groupBox_statut.setObjectName("groupBox_statut")
        self.lbl_status = QtWidgets.QLabel(self.groupBox_statut)
        self.lbl_status.setGeometry(QtCore.QRect(0, 20, 331, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_status.setFont(font)
        self.lbl_status.setAutoFillBackground(False)
        self.lbl_status.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_status.setObjectName("lbl_status")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 331, 61))
        self.groupBox_2.setObjectName("groupBox_2")
        self.pgr_level = QtWidgets.QProgressBar(self.groupBox_2)
        self.pgr_level.setGeometry(QtCore.QRect(10, 20, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pgr_level.setFont(font)
        self.pgr_level.setMinimum(0)
        self.pgr_level.setMaximum(4)
        self.pgr_level.setProperty("value", 0)
        self.pgr_level.setInvertedAppearance(False)
        self.pgr_level.setObjectName("pgr_level")
        self.groupBox_orientation = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_orientation.setGeometry(QtCore.QRect(10, 170, 331, 61))
        self.groupBox_orientation.setObjectName("groupBox_orientation")
        self.lbl_orientation = QtWidgets.QLabel(self.groupBox_orientation)
        self.lbl_orientation.setGeometry(QtCore.QRect(0, 20, 331, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_orientation.setFont(font)
        self.lbl_orientation.setAutoFillBackground(False)
        self.lbl_orientation.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_orientation.setObjectName("lbl_orientation")
        self.lbl_connection_status = QtWidgets.QLabel(self.centralwidget)
        self.lbl_connection_status.setGeometry(QtCore.QRect(40, 310, 55, 16))
        self.lbl_connection_status.setObjectName("lbl_connection_status")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 350, 26))
        self.menubar.setObjectName("menubar")
        self.menuApplication = QtWidgets.QMenu(self.menubar)
        self.menuApplication.setObjectName("menuApplication")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menu_serial_parameter = QtWidgets.QAction(MainWindow)
        self.menu_serial_parameter.setObjectName("menu_serial_parameter")
        self.menuApplication.addAction(self.menu_serial_parameter)
        self.menubar.addAction(self.menuApplication.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Boite Secrète"))
        self.btn_start.setText(_translate("MainWindow", "Start"))
        self.groupBox_statut.setTitle(_translate("MainWindow", "Statut"))
        self.lbl_status.setText(_translate("MainWindow", "OFF"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Niveau"))
        self.pgr_level.setFormat(_translate("MainWindow", "%v"))
        self.groupBox_orientation.setTitle(_translate("MainWindow", "Orientation de la boite"))
        self.lbl_orientation.setText(_translate("MainWindow", "OFF"))
        self.lbl_connection_status.setText(_translate("MainWindow", "Connexion : off"))
        self.menuApplication.setTitle(_translate("MainWindow", "Application"))
        self.menu_serial_parameter.setText(_translate("MainWindow", "Paramètres Série"))

